apiVersion: v1
data:
  script.sh: |-
    mysql -u mysqluser -h mysql.totalwine.svc.cluster.local --password=mysqlpw <<EOF  
    use demo; 
    insert into member (full_name, birthdate, account_hash, modifiedTS) values ('kenton t davis', '2008-7-04', 10001, CURDATE());
    insert into member (full_name, birthdate, account_hash, modifiedTS) values ('jon snow', '2018-1-14', 10006, CURDATE());
    insert into member (full_name, birthdate, account_hash, modifiedTS) values ('sallie mae', '2004-8-23', 10001, NOW());
    insert into member (full_name, birthdate) values ('sallie mae', '2004-8-23');
    update member set account_hash=10002 where full_name = 'sallie mae';
    delete from member where account_hash=10006;
    commit;
    EOF
kind: ConfigMap
metadata:
  name: script-demo-cdc
---
apiVersion: batch/v1
kind: Job
metadata:
  name: demo-cdc
spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: 180
  template:
    spec:
      containers:
        - command:
            - "sh"
            - "/opt/script/script.sh"
          envFrom:
            - configMapRef:
                name: connect-properties
          image: <CONTAINER_REGISTRY_PATH>/database-client:latest
          imagePullPolicy: IfNotPresent
          name: load-mysql-connector
          volumeMounts:
            - mountPath: /opt/script
              name: script-demo-cdc
              readOnly: false

      imagePullSecrets:
        - name: regcred

      restartPolicy: Never
      volumes:
        - configMap:
            name: script-demo-cdc
          name: script-demo-cdc

